#!/usr/bin/env python

import CameraServer
import sys

# make sure that it is being used properly
if len(sys.argv) != 2:
    print("usage: ./run <service port>")
    sys.exit()

# extract the script and service port from the args
script, service_port = sys.argv
service_port = int(service_port)

try:
    camera_server = CameraServer.CameraServer(service_port, False)
    camera_server.start_listening()
except KeyboardInterrupt:
    camera_server.write_to_log('KeyboardInterrupt detected, shutting down.')

camera_server.tear_down()

print('Have a great day :D')
sys.exit()
